### ISSUE TITLE
Add ability to generate a single file

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/governance#11]
Currently, running the `generate` tool will always write all files relevant for the version selected (base or uses-js). However, when we need to update just one or two files in a repository this is quite tedious. We should be able to specify a single file to update, or perhaps a comma-separated list of files to update, and only update those.

**Comment by thomashoneyman** [comment]
Not able to assign this to @gillchristian for some reason, but this issue is taken.

**Comment by milesfrain** [comment]
I believe you can only assign to non-org members if they made at least one comment on the issue.

**Comment by gillchristian** [comment]
> I believe you can only assign to non-org members if they made at least one comment on the issue.

This should do 😅
