### ISSUE TITLE
Update Contributors libraries according to library guidelines

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/governance#13]
@milesfrain, @JordanMartinez, and I have been undertaking an effort to ensure all Contributors libraries [meet the Library Guidelines](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md), with the ultimate goal of ensuring these libraries are documented, tested, and welcoming to users as well as potential contributors.

**Note: If you are interested in helping maintain any particular libraries, make sure to watch the repository.**

This issue tracks progress on at least ensuring the libraries share the same structure, have CI via GitHub Actions, have their latest version published to Pursuit, use Spago for local development, and so on.

**Checklist**

Please see the [library update checklist](https://github.com/purescript-contrib/governance/blob/main/updater/UpdateChecklist.md) for the steps to take to update any library in this list.

**Initial Library List [ Completed! ]**

This list of libraries is our test case to get a feel for how we should update the remaining libraries.

- [x] https://github.com/purescript-contrib/purescript-argonaut
- [x] https://github.com/purescript-contrib/purescript-argonaut-core
- [x] https://github.com/purescript-contrib/purescript-argonaut-traversals
- [x] https://github.com/purescript-contrib/purescript-argonaut-generic
- [x] https://github.com/purescript-contrib/purescript-argonaut-codecs
- [x] https://github.com/purescript-contrib/purescript-ace
- [x] https://github.com/purescript-contrib/purescript-js-timers
- [x] https://github.com/purescript-contrib/purescript-strings-extra
- [x] https://github.com/purescript-contrib/purescript-uri
- [x] https://github.com/purescript-contrib/purescript-machines

**Batch 1 [ Completed! ]**

This is the first set of libraries to update, which are a bit less-used in case we hit any extra snags.

- [x] https://github.com/purescript-contrib/purescript-freet ([PR](https://github.com/purescript-contrib/purescript-freet/pull/22))
- [x] https://github.com/purescript-contrib/purescript-string-parsers ([PR](https://github.com/purescript-contrib/purescript-string-parsers/pull/53))
- [x] https://github.com/purescript-contrib/purescript-form-urlencoded ([PR](https://github.com/purescript-contrib/purescript-form-urlencoded/pull/18))
- [x] https://github.com/purescript-contrib/purescript-these ([PR](https://github.com/purescript-contrib/purescript-these/pull/26))
- [x] https://github.com/purescript-contrib/purescript-options
- [x] https://github.com/purescript-contrib/purescript-http-methods
- [x] https://github.com/purescript-contrib/purescript-precise
- [x] https://github.com/purescript-contrib/purescript-media-types
- [x] https://github.com/purescript-contrib/purescript-fixed-points
- [x] https://github.com/purescript-contrib/purescript-concurrent-queues
- [x] https://github.com/purescript-contrib/purescript-unsafe-reference
- [x] https://github.com/purescript-contrib/purescript-js-date
- [x] https://github.com/purescript-contrib/purescript-now
- [x] https://github.com/purescript-contrib/purescript-nullable

**Batch 2 [ Completed! ]**

Next, we'll update these more-used libraries:

- [x] https://github.com/purescript-contrib/purescript-arraybuffer-types
- [x] https://github.com/purescript-contrib/purescript-unicode
- [x] https://github.com/purescript-contrib/purescript-pathy
- [x] https://github.com/purescript-contrib/purescript-fork
- [x] https://github.com/purescript-contrib/purescript-formatters
- [x] https://github.com/purescript-contrib/purescript-avar
- [x] https://github.com/purescript-contrib/purescript-aff-bus
- [x] https://github.com/purescript-contrib/purescript-coroutines
- [x] https://github.com/purescript-contrib/purescript-aff-coroutines

**Batch 3 [ Completed! ]**

Finally, these libraries will take more care and should be left for last:

- [x] https://github.com/purescript-contrib/purescript-aff
- [x] https://github.com/purescript-contrib/purescript-affjax
- [x] https://github.com/purescript-contrib/purescript-react-dom
- [x] https://github.com/purescript-contrib/purescript-react
- [x] https://github.com/purescript-contrib/purescript-parsing
- [x] https://github.com/purescript-contrib/purescript-routing
- [x] https://github.com/purescript-contrib/purescript-css
- [x] https://github.com/purescript-contrib/purescript-matryoshka

**Comment by thomashoneyman** [comment]
Edit: the checklist has moved:

https://github.com/purescript-contrib/governance/blob/main/updater/UpdateChecklist.md

**Comment by JordanMartinez** [comment]
@thomashoneyman Minor typo here:
```diff
- git mv .github/pull_request_template .github/PULL_REQUEST_TEMPLATE.md
+ git mv .github/pull_request_template.md .github/PULL_REQUEST_TEMPLATE.md
```
Also, `spago init` should be `spago init -C` to remove comments by default.

I need further clarification on how to use the `contrib-updater` tool correctly in regards to the package name fields:
```
  --display-name STRING    How to render this library's name in .md files.
                           Default: '`package-name`'
  --title STRING           How to render this library's name in titles. Default:
                           'package-name'
```
Given I have package `purescript-foo`, what should `display-name` and `title` be? I assume it's this:
```bash
contrib-updater generate --display-name purescript-foo --title purescript-foo
```
However, you said `purescript-uri` should be `URI` in some cases. Based on the docs above, it wasn't clear to me when one should be used over the other.

I'll update this with more comments if I come across any.

**Comment by JordanMartinez** [comment]
I'm claiming `purescript-freet` and `purescript-string-parsers`.

**Comment by thomashoneyman** [comment]
One quick clarification — package names here are referring to the _Spago_ package name, ie. freet (instead of purescript-freet).

Usually, I supply a capitalized version of the package name as the title — “FreeT” or “String Parsers” — and don’t supply a display name at all (I use the default, which is the package name in backticks).

I only use a custom display name for some libraries like Halogen which are normally referred to by their proper name (Halogen) instead of the package name in backticks.

Thanks for catching those typos! Currently on my phone but I’ll come back and update that later.

**Comment by JordanMartinez** [comment]
> Usually, I supply a capitalized version of the package name as the title — “FreeT” or “String Parsers” — and don’t supply a display name at all (I use the default, which is the package name in backticks).

In other words, if the package is `purescript-foo-bar-baz`, you would use
```bash
contrib-updater generate --title "Foo Bar Baz" --maintainer thomashoneyman
```

To clarify, should we get our PR reviewed and approved by one of us before merging them in? Or just merge it as soon as it's done?

**Comment by thomashoneyman** [comment]
Yes, that’s what I would typically do. And yes I think they should be approved before merging.

**Comment by thomashoneyman** [comment]
I've updated to fix the typos and clean up the instructions a little bit.

**Comment by JordanMartinez** [comment]
Just documenting this:
* The package name used in code snippets (for example, the installation instructions) should be the same as that used in the `spago.dhall` file (ie. package-name)
* The package name used in README contents should be the same as that used in the `spago.dhall` file, with backticks (ie. `package-name`)
* The package name used in README titles should be the same as that used in the `spago.dhall` file, converted to title case without hyphens (ie. Package Name)
* If a package name needs to be rendered differently in the README files, then you can provide a different format with the `--display-title` and `--display-name` flags. For example, the `freet` library would title case as “Freet” but it really ought to be “FreeT”.

**Comment by JordanMartinez** [comment]
`purescript-these` is now done.

**Comment by thomashoneyman** [comment]
Could I get a review on https://github.com/purescript-contrib/purescript-form-urlencoded/pull/18?

**Comment by JordanMartinez** [comment]
Ah, sorry about that. I was wondering why you hadn't merged that yet, haha.

**Comment by JordanMartinez** [comment]
I'll take `nullable` next.

**Comment by JordanMartinez** [comment]
Taking `purescript-options`

**Comment by JordanMartinez** [comment]
Also taking `purescript-http-methods`

**Comment by thomashoneyman** [comment]
Due to #19 and #17, let's hold off on doing any further libraries at the moment.

**Comment by thomashoneyman** [comment]
OK! We can now continue working on the remainder of batch 1.

**Comment by JordanMartinez** [comment]
Sweet!

**Comment by thomashoneyman** [comment]
@maxdeviant took care of `media-types` (thank you!).

**Comment by maxdeviant** [comment]
`purescript-now` was completed in https://github.com/purescript-contrib/purescript-now/pull/14.

**Comment by thomashoneyman** [comment]
The remainder of Batch 1 is now complete. Please hold off on updating any libraries from Batch 2 until I have a chance to update their admin settings!

**Comment by thomashoneyman** [comment]
OK -- Batch 2 is now ready to go for anyone who would like to take one on.

**Comment by maxdeviant** [comment]
I'll take `purescript-arraybuffer-types`.

**Comment by thomashoneyman** [comment]
Ready for review (I'll merge by EOD tomorrow unless anyone catches issues):

- https://github.com/purescript-contrib/purescript-coroutines/pull/33
- https://github.com/purescript-contrib/purescript-aff-bus/pull/21
- https://github.com/purescript-contrib/purescript-avar/pull/21
- https://github.com/purescript-contrib/purescript-formatters/pull/58
- https://github.com/purescript-contrib/purescript-fork/pull/11
- https://github.com/purescript-contrib/purescript-pathy/pull/41
- https://github.com/purescript-contrib/purescript-unicode/pull/26

This (along with `arraybuffer-types`, handled by @maxdeviant) concludes Batch 2, and leaves us with just the last batch to go.

The automatic changelog generation, @JordanMartinez, is a _really_ nice addition.

**Comment by thomashoneyman** [comment]
I've updated the settings for Batch 3 and any of those libraries are also available to take on.

**Comment by maxdeviant** [comment]
I noticed that some of the repositories in Batch 3 (`purescript-aff`, `purescript-matryoshka`) don't have any maintainers listed in the README.

Who should we pass as the `--maintainer` in these cases?

**Comment by garyb** [comment]
@natefaubion is definitely one for `aff`, it's mostly his baby at this point.

You can put me down for `matryoshka`. I'm not an expert in recursion schemes although I authored this, based on the Scala library, so it'd be nice if there are any experts who would have an interest in helping out too. Or non experts! But having someone who can assess suitability of proposed modifications would be great.

**Comment by thomashoneyman** [comment]
@maxdeviant if there are no maintainers, you can definitely ask here about it, and otherwise we generally default to @garyb and myself until we find someone more suitable.

**Comment by JordanMartinez** [comment]
Just wanted to say nice job @thomashoneyman on doing all of those library updates!

**Comment by thomashoneyman** [comment]
Could use reviews for a few libraries:

- https://github.com/purescript-contrib/purescript-parsing/pull/98
- https://github.com/purescript-contrib/purescript-affjax/pull/153
- https://github.com/purescript-contrib/purescript-react/pull/176

**Comment by JordanMartinez** [comment]
parsing and affjax have been reviewed. I'm not familiar with react, so I think someone else should review it.

**Comment by thomashoneyman** [comment]
Also completed:

- https://github.com/purescript-contrib/purescript-react-dom/pull/18
- https://github.com/purescript-contrib/purescript-aff/pull/195

**Comment by thomashoneyman** [comment]
We've done it! All libraries are complete, as far as pull requests go, so I'm going to close this issue. There are three libraries that haven't had their updates merged yet but I need to wait for reviews from other maintainers on those libraries before taking any more action. With that in mind I'm going to go ahead and close this issue.

**Comment by maxdeviant** [comment]
![Party Parrot](https://media3.giphy.com/media/l3q2zVr6cu95nF6O4/source.gif)
