### ISSUE TITLE
Link to organization-wide issue search

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/governance#18]
Per #16, I propose we add the below link to this repo somewhere for people who want to know how they could help:

https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Apurescript-contrib

**Comment by thomashoneyman** [comment]
I'm on board. Where do you think it should go?

**Comment by JordanMartinez** [comment]
In the [how do I pick something to work on](https://github.com/purescript-contrib/governance/blob/main/contributing.md#id-like-to-help-how-do-i-pick-something-to-work-on) section?

**Comment by thomashoneyman** [comment]
That's a good place for it.
