### ISSUE TITLE
Fix libraries with incorrect CHANGELOG, CONTRIBUTING, and stale.yml files

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/governance#21]
These libraries need to be fixed to:

* Move the `CHANGELOG` file into the repository root and remove the link to it from the README
* Move the `CONTRIBUTING` file into the repository root and fix the links to it in the README and docs/README
* Remove the `.github/workflows/stale.yml` file

- [x] https://github.com/purescript-contrib/purescript-argonaut
- [x] https://github.com/purescript-contrib/purescript-argonaut-core
- [x] https://github.com/purescript-contrib/purescript-argonaut-traversals
- [x] https://github.com/purescript-contrib/purescript-argonaut-generic
- [x] https://github.com/purescript-contrib/purescript-argonaut-codecs
- [x] https://github.com/purescript-contrib/purescript-ace
- [x] https://github.com/purescript-contrib/purescript-js-timers
- [x] https://github.com/purescript-contrib/purescript-strings-extra
- [x] https://github.com/purescript-contrib/purescript-uri
- [x] https://github.com/purescript-contrib/purescript-machines
- [x] https://github.com/purescript-contrib/purescript-freet
- [x] https://github.com/purescript-contrib/purescript-string-parsers
- [x] https://github.com/purescript-contrib/purescript-form-urlencoded
- [x] https://github.com/purescript-contrib/purescript-these
- [x] https://github.com/purescript-contrib/purescript-options
- [x] https://github.com/purescript-contrib/purescript-http-methods
- [x] https://github.com/purescript-contrib/purescript-precise

I believe this should just happen via a commit directly to `main` rather than a PR, as it's a tiny change that doesn't need to notify all watchers of the repository.

**Comment by JordanMartinez** [comment]
> I believe this should just happen via a commit directly to main rather than a PR, as it's a tiny change that doesn't need to notify all watchers of the repository.

Agreed!

**Comment by JordanMartinez** [comment]
If this is a systematic change to all repos, I think we should build a tool that can make such changes via a single command. You're basically doing just this:
```purescript
doUpdate = for repos \repo -> do
  fork repo -- gh repo fork repo
  cd repo -- cd repo
  git mv .docs/CHANGELOG.md ./CHANGELOG.MD
  git commit -m "Moved changelog to root folder"
  git push
```
The `stale.yml` one would take a bit more work, but could likely be done in a similar fashion.

**Comment by thomashoneyman** [comment]
Libraries are all updated! There's quite a proliferation of files in the root now, unfortunately, but I think they're all serving a purpose. It'll be nice to remove the `bower.json` files later on.
