### ISSUE TITLE
Add CI for the contrib-updater CLI tool

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/governance#27]
The updater tool currently doesn't have any tests or continuous integration running on pull requests. We should at least ensure that the tool compiles successfully, and we can follow up with more sophisticated CI in the future. 

This could be done with a fairly standard `setup-purescript` configuration [following that project's README](github.com/purescript-contrib/setup-purescript).

**Comment by gillchristian** [comment]
I can take this one
