### ISSUE TITLE
Fix warnings in contrib libraries revealed by v0.14.1 PS release

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/governance#37]
See purescript/purescript#4071 for more context. Here's the list I have using the same methodology:

- [x] argonaut-generic
- [x] css
- [x] formatters
- [x] machines
- [x] parsing
- [x] pathy
- [x] precise
- [x] profunctor-lenses
- [x] quickcheck-laws
- [x] routing
- [x] strings-extra
- [x] uri

## Node and Web Libs

- [x] node-buffer
- [x] node-fs
- [x] node-process
- [x] web-dom-xpath
- [x] web-html
- [x] web-xhr

**Comment by JordanMartinez** [comment]
I've added node and web libraries above, too. The list might be incomplete because I only searched for all libs that started with `node-` or `web-` rather than using my original Vlookup approach.

**Comment by JordanMartinez** [comment]
PRs to all contrib libraries have been submitted.

**Comment by JordanMartinez** [comment]
All node libraries' PRs have been submitted. Can we start merging some of these open PRs?

**Comment by thomashoneyman** [comment]
@JordanMartinez Everything except for `precise` has been merged and released.

**Comment by JordanMartinez** [comment]
@thomashoneyman Thanks!

**Comment by f-f** [comment]
Thank you both for doing this! :heart:
