### ISSUE TITLE
purescript-long?

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-contrib/governance#42]
This package https://github.com/zapph/purescript-longs

has important features but it gives me lots of trouble because of the way it’s organized. Also the package is not receiving any attention from its author.

How would we feel about a __purescript-contrib/purescript-long__ package which is basically the same thing, but with types `Long` and `ULong` instead of of the parameterized types `Long Signed` and `Long Unsigned`?

**Comment by jamesdbrock** [comment]
This all depends on https://www.npmjs.com/package/long , so maybe it's not a good choice for inclusion in __purescript-contrib__?

**Comment by JordanMartinez** [comment]
I think I'd be ok with this. It may be wrapping a JS library, but it is also providing "core data types" similar to the other ones that were transferred recently. Plus, the `contrib` org isn't the core libraries.

**Comment by jamesdbrock** [comment]
I've written a replacement for __purescript-long__ called __purescript-int64__. I intend to add it to contrib, is that cool?

https://github.com/jamesdbrock/purescript-int64

This package has no NPM.js dependencies, instead I've just copied the NPM code into this package. https://github.com/jamesdbrock/purescript-int64/tree/main/src/Data/Internal/long.js

This would go along with our other packages for “core data types”:

* https://github.com/purescript-contrib/purescript-float32
* https://github.com/purescript-contrib/purescript-uint

**Comment by jamesdbrock** [comment]
Published https://github.com/purescript-contrib/purescript-int64

**Comment by JordanMartinez** [comment]
Thanks James!
