### ISSUE TITLE
Migrate 'make-changelog-from-release-notes' repo code into here

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/governance#51]
https://github.com/JordanMartinez/make-changelog-from-release-notes

**Comment by JordanMartinez** [comment]
This code generates an initial CHANGELOG.md file using the GitHub release notes when a new repo is transferred into the contrib org.

**Comment by thomashoneyman** [comment]
Is this not usable?

https://github.com/purescript-contrib/governance/blob/main/updater/src/Updater/Generate/Changelog.purs

**Comment by JordanMartinez** [comment]
Hm.... I think I forgot this was already ported here, so I thought I had to run it separately. I likely ran that script before running `contrib-update generate`.
